### ISSUE TITLE
Un-deprecate isInstanceOf

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/matcher#103]
https://www.dartlang.org/guides/language/effective-dart/design#consider-making-the-code-read-like-a-sentence

"expect(myOutput, isInstanceOf<String>())" reads significantly more like a sentence than "expect(myOutput, const TypeMatcher<String>())"

**Comment by natebosch** [comment]
If we had the current `isInstanceOf` out of the way and we could define a method with that name I'd probably say it would be the right design.

As is I'm not sure I like the idea of leaving a non-capitalized class without a deprecation warning.

@kevmoo - thoughts?

**Comment by kevmoo** [comment]
If/when we're ready to do matcher v2 (and test v2 by extension) I fully
support that.

**Comment by natebosch** [comment]
@kevmoo - what do you think about introducing an alternative name so that it can still read like a sentence?

```dart
TypeMatcher<T> isA<T>() => TypeMatcher<T>();

expect(myOutPut, isA<Foo>());
```

**Comment by kevmoo** [comment]
SGTM!

**Comment by natebosch** [comment]
cc @Hixie - `isA` would be a new top level symbol in package:test - any concerns?

**Comment by natebosch** [comment]
This would be a replacement for `isInstanceOf` that we can move forward with without a breaking version bump. They'd both exist in the package until such time as we can delete `isInstanceOf` in the next breaking version bump.

If we want to move to test `2.0.0` and have a breaking change in `isInstanceOf` (_disallow_ the `new` and make it a method instead of a class) we could go with that and keep that name instead of `isA`. If we want an incremental migration - make the expected long term option available now - then we need a different name.

**Comment by Hixie** [comment]
As far as Flutter is concerned, we've already migrated our users to `isInstanceOf` without the `new`.
