### ISSUE TITLE
Feature Request: isAssertionError

### ISSUE THREAD

**Issue by srawlins** [dart-lang/matcher#64]
As an [AssertionError](https://api.dartlang.org/stable/1.24.3/dart-core/AssertionError-class.html) is thrown when an `assert` is given `false`, which is a core language thing, it would be nice to have a handy `throwsAssertionError` matcher.

**Comment by nex3** [comment]
What's your use-case? It doesn't seem like it would usually be safe to test for an `AssertionError`, since you may be running in unchecked mode where the assertion wouldn't fire.

**Comment by natebosch** [comment]
It does seem a bit odd to treat an assertion error as a part of your testable API... But we have people doing it, so we may as well let them do it with a standard tool. I've seen this type of test pop up a few times

**Comment by nex3** [comment]
Testing assertion errors introduces a behavioral difference between tests run with `pub run test` (which uses checked mode) and `dart path/to/test.dart` (which doesn't by default). I don't think that's something we want to encourage. Since it's pretty easy to write `new isInstanceOf<AssertionError>()` anyway, I'd like to keep this as-is.

**Comment by srawlins** [comment]
I'll reopen when we're [Dart 2.0](https://www.dartlang.org/dart-2.0#obsolete-features).

**Comment by nex3** [comment]
:+1:, assuming assertions are enabled by default.

**Comment by BugsBunnyBR** [comment]
So, can we have `isAssertionError` now that dart 2.0 is out?

**Comment by srawlins** [comment]
I think I wrote that comment under the impression that asserts were going to be always enabled in Dart 2.0, but that is not correct.
