### ISSUE TITLE
Document (and test) usage of `expect` calls within a predicate function

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/matcher#66]
https://github.com/dart-lang/matcher/blob/fc06eae818c0602b6ea2b391bce613cb6654373e/lib/src/core_matchers.dart#L580

Would be much easier in testing exceptions.

...should make sure they work as intended...

**Comment by nex3** [comment]
There's nothing at all special about `expect()` in `predicate()`. It's not really how the API is intended to be used, it just comes up in practice as a workaround for custom matchers being such a pain to define (see #6). But there's nothing here to test, other than the fact that anonymous functions can contain arbitrary statements, which is part of the language rather than part of `matcher`.
